url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Cannabis Equity Illinois Coalition" # the name of your site, e.g. ACME Corp.
sass:
  style: compressed

plugins:
  - jekyll-seo-tag
